### ISSUE TITLE
output differs from codeforces and runtime_error usually

### ISSUE THREAD

**Issue by emanuele-em** [rust-competitive-helper/rust-competitive-helper#12]
I don't know why but on codeforces the output add (only sometimes) a 0 at the beginning, sometimes a runtime_error with exit code 101 occurs on codeforces while on vscode it runs perfectly

I tried to `rustup override 1.66.0` in the folder but nothing changes 🤔

**Comment by mdacach** [comment]
Did you find a workaround? I am having the same problem - works fine on my machine, but runtime_error on Codeforces. Running the same test on Codeforces' Custom Test produces no output.

**Comment by bminaiev** [comment]
In this specific case, which @emanuele-em had, `input.read_line()` and `input.read()` were used at the same time, and they don't work nicely together. 

But probably you have some different issue. Could you share your code/input?

Usually using Codeforces' custom test is the best option for debugging in this case. You can add some debug output. E.g. first print some message at the very begging (just to make sure that you see it), then print a message after reading input with information about what you read, and so on.

**Comment by emanuele-em** [comment]
Simply never use read_line()

Just use read() or read_vec()

With read_line() there are some problems with EOL
